---
apiVersion: v1
kind: Service
metadata:
  name: cluster-upgrade-calendar-backend
  namespace: open-cluster-management
  labels:
    app.kubernetes.io/name: cluster-upgrade-calendar
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    app.kubernetes.io/name: cluster-upgrade-calendar
    app.kubernetes.io/component: backend